version: '3'
services:
  db1:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
      MYSQL_USER: root1
      MYSQL_PASSWORD: root1
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - back


  restful-web-services:
    build: ./restful-web-services
    container_name: restful-web-services
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db1:3306/sandbox?useSSL=false
        SPRING_DATASOURCE_USERNAME: root1
        SPRING_DATASOURCE_PASSWORD: root1
    ports:
      - 8080:8080
    depends_on:
      - db1 # This service depends on mysql. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - back
      - front
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 4200:4200
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - front

volumes:
  db:

networks:
  back:
  front:
    driver: bridge
